# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - bourbon
  
# Site settings
title: "Design Theory"
description: > # this means to ignore newlines until "email:"
   GRAPHICS.ANIMATION.DESIGN

email: rama.ksriram@gmail.com
#blog logo
logo: "/assets/images/DT_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'K.Ramachandran'
author: 'K.Ramachandran'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/ramaksriram
    desc: Follow me on twitter
    share_url: http://twitter.com/ramaksriram
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://www.facebook.com/K.Ramachandran
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/designtheory
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
